modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "${modGitHubUrl}/issues"
clientSideOnly = true

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
displayURL = "${modGitHubUrl}"
authors = "MarcPG"
description = """
${modDescription}
"""

bannerFile = "icon.png"
iconFile = "icon.png"
iconBlur = true
logoFile = "icon.png"
logoBlur = true

[[mixins]]
config = "${modId}.normal.mixins.json"

[[mixins]]
config = "${modId}.compat.mixins.json"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[${minMinecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "freecam"
type = "optional"
versionRange = "[1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "freecam_by_jasonzli"
type = "optional"
versionRange = "[1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "freecam_by_kapiteon"
type = "optional"
versionRange = "[1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "zergatulfreecam"
type = "optional"
versionRange = "[1,)"
ordering = "AFTER"
side = "CLIENT"
